version: '3.9'

services:
  postgresql_db:
    image: postgres:alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
